# Generated by Django 5.2.11 on 2026-02-26 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='编号')),
                ('price', models.FloatField(verbose_name='每小时租赁价格')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '滑板车',
                'verbose_name_plural': '滑板车',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否支付')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooter.scooter', verbose_name='租赁滑板车')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
