# Generated by Django 5.2.11 on 2026-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='price',
        ),
        migrations.AddField(
            model_name='scooter',
            name='price_1d',
            field=models.FloatField(default=0.0, verbose_name='1天价格'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='price_1h',
            field=models.FloatField(default=0.0, verbose_name='1小时价格'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='price_1w',
            field=models.FloatField(default=0.0, verbose_name='1周价格'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='price_4h',
            field=models.FloatField(default=0.0, verbose_name='4小时价格'),
        ),
    ]
