# Generated by Django 5.2.11 on 2026-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0002_remove_scooter_price_scooter_price_1d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='hire_period',
            field=models.CharField(choices=[('1h', '1小时'), ('4h', '4小时'), ('1d', '1天'), ('1w', '1周')], default='1h', max_length=2, verbose_name='租赁时长'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='unpaid', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='订单总价'),
        ),
    ]
