# Generated by Django 5.2.11 on 2026-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0003_remove_order_is_paid_order_hire_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='编号'),
        ),
    ]
