# Generated by Django 5.2.11 on 2026-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0004_alter_scooter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='订单总价'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='price_1d',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='1天价格'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='price_1h',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='1小时价格'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='price_1w',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='1周价格'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='price_4h',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='4小时价格'),
        ),
    ]
