# Generated by Django 5.2.11 on 2026-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0005_alter_order_total_price_alter_scooter_price_1d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hire_period',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='price_1d',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='price_1h',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='price_1w',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='price_4h',
        ),
        migrations.AddField(
            model_name='order',
            name='new_hire_period',
            field=models.PositiveIntegerField(default=1, verbose_name='租赁小时数'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='min_hire_hours',
            field=models.PositiveIntegerField(default=1, verbose_name='最低起租小时数'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='基础小时单价（¥/小时）'),
        ),
    ]
