# Generated by Django 5.2.11 on 2026-04-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0006_remove_order_hire_period_remove_scooter_price_1d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='new_hire_period',
            new_name='hire_period',
        ),
    ]
