# Generated by Django 5.2.11 on 2026-04-09 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0010_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='问题描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已解决')], default='pending', max_length=10, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooter.scooter', verbose_name='故障车辆')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '故障反馈',
                'verbose_name_plural': '故障反馈',
            },
        ),
    ]
