# Generated by Django 5.2.11 on 2026-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='address',
            field=models.CharField(default='City Centre', max_length=100),
        ),
        migrations.AddField(
            model_name='scooter',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scooter',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
