<<<<<<< Updated upstream
# Generated by Django 5.2.11 on 2026-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0012_scooter_address_scooter_latitude_scooter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='address',
            field=models.CharField(default='City Centre', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='经度'),
        ),
    ]
=======
# Generated by Django 5.2.11 on 2026-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0012_scooter_address_scooter_latitude_scooter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='address',
            field=models.CharField(default='City Centre', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='经度'),
        ),
    ]
>>>>>>> Stashed changes
