# Generated by Django 5.2.11 on 2026-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0013_alter_scooter_address_alter_scooter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('low', '低优先级'), ('high', '高优先级')], default='low', max_length=10, verbose_name='优先级'),
        ),
    ]
