# Generated by Django 5.2.11 on 2026-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0014_feedback_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scooters/', verbose_name='车辆图片'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='performance',
            field=models.TextField(blank=True, default='', verbose_name='性能描述'),
        ),
    ]
