# Generated by Django 5.2.11 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0015_scooter_image_scooter_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='performance_en',
            field=models.TextField(blank=True, default='', help_text='可选，用于英文界面显示', verbose_name='性能描述 (English)'),
        ),
    ]
